# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0831b3c684635f4fa77761b8661a76381c3589fb893b20a5da4e9816d526d863e403eecc5076f4bcc3cf2fa308dbd40fdc3ac6432e3651185fe96eded71657e1

test:
  secret_key_base: af81b46a519b046412f3f288cc3b5c5c24a210438dc0bde84de9a861131be0439dfd7d279298044430550ebcbacaa5023539726eb3541354b16dd225bca42bfc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
